### ISSUE TITLE
Comparison to other projects

### ISSUE THREAD

**Issue by dancancro** [born2net/Angular-kitchen-sink#32]
This is a great project. I entered selling points of this project and I made the following comparison of a few projects to show how they differ. If you have any corrections to make you can do so by commenting in the [spreadsheet](https://docs.google.com/spreadsheets/d/1nMv8TqUx3gUoC3M6BRPB4E4FMTSYGT_OLERguXGjePc/edit#gid=1404564369) from which this is generated. If you are wondering whey I went to such lengths it's not to promote a particular project. It's because I want people to stop competing and start working together. It is overwhelming to learners who have to pick a starting point and causes unnecessary duplication of work by the disagreeing project owners.

| **Benefits** |[Angular-kitchen-sink](https://github.com/born2net/Angular-kitchen-sink)|[great big angular2 example](https://github.com/dancancro/great-big-angular2-example)|[ngrx example app](https://github.com/ngrx/example-app)|[angular2-redux-starter](https://github.com/rangle/angular2-redux-starter)|[angular-seed-advanced](https://github.com/NathanWalker/angular-seed-advanced)|
|:------ | :------: | :------: | :------: | :------: | :------: |
|Angular/redux project | ng2-redux |ngrx |ngrx |ng2-redux |ngrx |
[Account Management, Forgotten Password with Resetting](https://github.com/meanjs/mean/issues/30)|[Y](https://github.com/born2net/Angular-kitchen-sink/blob/08ff94405b80ee24acff09d0de270e56ba4bace2/src/comps/entry/ForgotPass.ts)| | | | |
[Account Management, login/logout](https://github.com/born2net/Angular-kitchen-sink/blob/65b01608a769578a94850bc39254d7e81f82d239/src/comps/entry/EntryPanel.ts)|[Y](https://github.com/born2net/Angular-kitchen-sink/blob/65b01608a769578a94850bc39254d7e81f82d239/src/comps/entry/EntryPanel.ts)|Y| |[Y](https://github.com/rangle/angular2-redux-example/tree/master/src/components/login)| |
[Analytics](https://github.com/NathanWalker/angular-seed-advanced)|[Y](https://www.google.com/analytics)|[Y](https://www.google.com/analytics)| | |[Y](https://github.com/NathanWalker/angular-seed-advanced)|
[Asynchronously loaded data example](https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/core/store/data.service.ts#L32)|Y|[Y](https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/core/store/data.service.ts#L32)|Y| |Y|
[Authentication](https://www.linkedin.com/groups/Authentication-Angular-5010991.S.5939860671763070977)|[Y](https://github.com/born2net/Angular-kitchen-sink/blob/7260a89a3f968243e642b20c9fd6775ba59eaf41/src/services/DefaultAuthService.ts)|[Y](https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/core/store/session/session.effects.ts#L26)| |[Y](https://github.com/rangle/angular2-redux-example/blob/master/src/epics/session.epics.ts#L20)| |
[Authentication, with two-factor authentication](https://github.com/born2net/Angular-kitchen-sink/blob/08ff94405b80ee24acff09d0de270e56ba4bace2/src/actions/SampleActions.js#L22)|[Y](https://github.com/born2net/Angular-kitchen-sink/blob/08ff94405b80ee24acff09d0de270e56ba4bace2/src/actions/SampleActions.js#L22)| | | | |
[Breadcrumbs](https://github.com/born2net/Angular-kitchen-sink/tree/master/src/comps/breadcrumb)|[Y](https://github.com/born2net/Angular-kitchen-sink/tree/master/src/comps/breadcrumb)| | | | |
[Buttons](http://208.68.38.122/themes/emerald/dev/htmls/elements/buttons.html)|[Y](https://material.angularjs.org/latest/demo/button)| | | | |
Charts|Y| | | | |
[Client-side unit tests](https://github.com/born2net/Angular-kitchen-sink/blob/132ddece2635d13e983ce873742ba962fc5c7fce/src/app/app.component.spec.ts)|[Y](https://github.com/born2net/Angular-kitchen-sink/blob/132ddece2635d13e983ce873742ba962fc5c7fce/src/app/app.component.spec.ts)| | |[Y](https://github.com/rangle/angular2-redux-example/blob/master/src/components/button/button.component.test.ts)|[Y](https://github.com/NathanWalker/angular-seed-advanced/blob/master/src/client/app/components/app.component.spec.ts)|
[Code coverage reporting](http://blog.johnryding.com/post/46757192364/javascript-code-coverage-with-phantomjs-jasmine-and)|[Y](http://mochajs.org/)|[Y](http://mochajs.org/)| |Y| |
[Command line interface (CLI)](https://github.com/Hashnode/mern-cli)|Y|Y| |Y| |
[Components communicate with events](https://github.com/born2net/Angular-kitchen-sink/blob/65b01608a769578a94850bc39254d7e81f82d239/src/comps/app3/starwars/components/films-component.ts#L11)|[Y](https://github.com/born2net/Angular-kitchen-sink/blob/65b01608a769578a94850bc39254d7e81f82d239/src/comps/app3/starwars/components/films-component.ts#L11)|Y|Y| | |
[Core Module](https://angular.io/docs/ts/latest/guide/style-guide.html#!#04-12)| |[Y](https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/core/core.module.ts)| | | |
CSS style checking| |Y| | | |
[Date picker](https://youtu.be/d1MEM8PdAzQ?t=964)|[Y](https://material.angularjs.org/latest/demo/datepicker)| | | | |
[Deployment automation, to a native executable](https://github.com/NathanWalker/angular-seed-advanced#electron-app)| | | | |[Y](https://github.com/NathanWalker/angular-seed-advanced#electron-app)|
[Deployment automation, using Docker](https://www.docker.io/)| | | |[Y](https://github.com/rangle/angular2-redux-example/blob/master/Dockerfile)|[Y](https://github.com/NathanWalker/angular-seed-advanced/blob/master/docker-compose.production.yml)|
[Deployment automation, using Github Pages](https://github.com/angular/angular-cli)|[Y](https://github.com/angular/angular-cli)|[Y](https://github.com/angular/angular-cli)| | | |
[Derived, computed properties](https://github.com/born2net/Angular-kitchen-sink/blob/master/src/models/ServerModel.js#L35)|[Y](https://github.com/born2net/Angular-kitchen-sink/blob/master/src/models/ServerModel.js#L35)|[Y](https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/core/store/claim/claim.model.ts#L27-L29)| | | |
[Dropdowns](http://valor-software.com/ng2-bootstrap/#/dropdowns)|[Y](http://valor-software.com/ng2-bootstrap/#/dropdowns)| | | | |
[Dynamic component creation](https://github.com/born2net/Angular-kitchen-sink/tree/08ff94405b80ee24acff09d0de270e56ba4bace2/src/comps/dynmiaccomp)|[Y](https://github.com/born2net/Angular-kitchen-sink/tree/08ff94405b80ee24acff09d0de270e56ba4bace2/src/comps/dynmiaccomp)| | | | |
[End-to-end tests](https://github.com/born2net/Angular-kitchen-sink/tree/master/e2e)|[Y](https://github.com/born2net/Angular-kitchen-sink/tree/master/e2e)| | |[Y](https://github.com/rangle/angular2-redux-example/tree/master/e2e/robot)|[Y](https://github.com/NathanWalker/angular-seed-advanced/tree/master/src/e2e)|
[External, 3rd party, API interaction](https://github.com/born2net/Angular-kitchen-sink/blob/master/src/services/SearchSpotifyService.ts)|[Y](https://github.com/born2net/Angular-kitchen-sink/blob/master/src/services/SearchSpotifyService.ts)|Y|Y| | |
[Footer](https://github.com/born2net/Angular-kitchen-sink/blob/08ff94405b80ee24acff09d0de270e56ba4bace2/src/comps/footer/Footer.ts)|[Y](https://github.com/born2net/Angular-kitchen-sink/blob/08ff94405b80ee24acff09d0de270e56ba4bace2/src/comps/footer/Footer.ts)| | | | |
[Full-stack CRUD](https://github.com/born2net/Angular-kitchen-sink/tree/65b01608a769578a94850bc39254d7e81f82d239/src/comps/app1/todos)|[Y](https://github.com/born2net/Angular-kitchen-sink/tree/65b01608a769578a94850bc39254d7e81f82d239/src/comps/app1/todos)|Y| | | |
[Full-stack CRUD, with Create, Update and Delete](https://github.com/born2net/Angular-kitchen-sink/tree/65b01608a769578a94850bc39254d7e81f82d239/src/comps/app1/todos)|[Y](https://github.com/born2net/Angular-kitchen-sink/tree/65b01608a769578a94850bc39254d7e81f82d239/src/comps/app1/todos)|Y| | | |
[Full-stack CRUD, with Create, Update and Delete, individual records](https://github.com/born2net/Angular-kitchen-sink/tree/65b01608a769578a94850bc39254d7e81f82d239/src/comps/app1/todos)|[Y](https://github.com/born2net/Angular-kitchen-sink/tree/65b01608a769578a94850bc39254d7e81f82d239/src/comps/app1/todos)|Y| | | |
Full-stack CRUD, with Create, Update and Delete, whole data structures| |Y| | | |
[Full-stack CRUD, with Read](https://github.com/born2net/Angular-kitchen-sink/tree/65b01608a769578a94850bc39254d7e81f82d239/src/comps/app1/todos)|[Y](https://github.com/born2net/Angular-kitchen-sink/tree/65b01608a769578a94850bc39254d7e81f82d239/src/comps/app1/todos)|Y| | | |
[Grid, Editable](https://github.com/dancancro/great-big-angular2-example/tree/master/src/app/debate)| |[Y](https://github.com/dancancro/great-big-angular2-example/tree/master/src/app/debate)| | | |
[i18n, localization](http://mean.io/#!/packages/538790d7a331eb26d1e97d3b)| | | | |Y|
[Images, Carousel](http://valor-software.com/ng2-bootstrap/#/)|[Y](http://valor-software.com/ng2-bootstrap/#/)| | | | |
In-memory server-side database|Y|[Y](http://expressjs.com/guide/database-integration.html)| |[Y](http://expressjs.com/guide/database-integration.html)|[Y](http://expressjs.com/guide/database-integration.html)|
[Local storage](https://github.com/born2net/Angular-kitchen-sink/blob/65b01608a769578a94850bc39254d7e81f82d239/src/services/LocalStorage.ts)|[Y](https://github.com/born2net/Angular-kitchen-sink/blob/65b01608a769578a94850bc39254d7e81f82d239/src/services/LocalStorage.ts)|[Y](https://github.com/dancancro/great-big-angular2-example/blob/e29a656b8f923ad9fb5867288f4628674994b697/src/app/core/store/index.ts#L123)|Y|Y| |
[Many-to-many data](https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/core/store/index.ts#L265)| |[Y](https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/core/store/index.ts#L265)| | | |
[Modals (popups, dialogs)](https://material.angularjs.org/latest/demo/dialog)|[Y](https://material.angularjs.org/latest/demo/dialog)| | | | |
[Mouse wheel](https://github.com/born2net/Angular-kitchen-sink/blob/08ff94405b80ee24acff09d0de270e56ba4bace2/src/comps/Mousewheel/Mousewheel.ts)|[Y](https://github.com/born2net/Angular-kitchen-sink/blob/08ff94405b80ee24acff09d0de270e56ba4bace2/src/comps/Mousewheel/Mousewheel.ts)| | | | |
[Navigation bar](https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/app.page.html)|[Y](https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/app.page.html)|[Y](https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/app.page.html)|[Y](https://github.com/ngrx/example-app/blob/master/src/app/containers/app.ts#L15)| | |
[Panels, collapsible (accordian)](https://codegeekz.com/10-best-angularjs-frameworks/)|[Y](http://valor-software.com/ng2-bootstrap/#/)| | | | |
[Panels, draggable](https://github.com/born2net/Angular-kitchen-sink/blob/65b01608a769578a94850bc39254d7e81f82d239/src/comps/dragndrop/make-draggable.directive.ts)|[Y](https://github.com/born2net/Angular-kitchen-sink/blob/65b01608a769578a94850bc39254d7e81f82d239/src/comps/dragndrop/make-draggable.directive.ts)|Y| | | |
[Persistent data storage](http://hammerprinciple.com/databases)| |[Y](http://expressjs.com/guide/database-integration.html)| |[Y](http://expressjs.com/guide/database-integration.html)|[Y](http://expressjs.com/guide/database-integration.html)|
[Popover](http://valor-software.com/ng2-bootstrap/#/popover)|[Y](http://valor-software.com/ng2-bootstrap/#/popover)| | | | |
[Production build, generate docs](https://github.com/yeoman/yeoman/issues/152)|Y| | | | |
[Progress bars](http://208.68.38.122/themes/emerald/dev/htmls/elements/components.html#)|[Y](https://material.angularjs.org/latest/demo/progressLinear)| | | | |
[Rating, scale](http://valor-software.com/ng2-bootstrap/#/rating)|[Y](http://valor-software.com/ng2-bootstrap/#/rating)| | | | |
[Responsive styles](https://github.com/dancancro/great-big-angular2-example/blob/166ae9353bd6ff34badbc045b2044cf417c6d8c5/src/assets/styles/flexbox.css#L4)|Y|[Y](https://github.com/dancancro/great-big-angular2-example/blob/166ae9353bd6ff34badbc045b2044cf417c6d8c5/src/assets/styles/flexbox.css#L4)| |[Y](https://github.com/rangle/angular2-redux-example/blob/2c541e5ce057111c32464ccee3624ab50d84f084/src/components/modal/modal.css#L7)| |
[Search, actually works with backend API](https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/books/book-search/book-search.component.ts)| |[Y](https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/books/book-search/book-search.component.ts)|[Y](https://github.com/ngrx/example-app/blob/master/src/app/components/book-search.ts)| | |
[Separation of smart containers and dumb components](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.vkyyo356c)| |Y|Y| | |
[Server-side integration & unit tests](http://www.letscodejavascript.com/v3/episodes/live/1)|Y|Y| | | |
[Shared Module](https://angular.io/docs/ts/latest/guide/style-guide.html#!#04-10)|[Y](https://github.com/born2net/Angular-kitchen-sink/blob/8cc88024f22156f397f2aa95dc142460f720f50f/src/comps/app1/lazyone/SharedModule.ts)|[Y](https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/shared/shared.module.ts)| | | |
[Slider](http://webapplayers.com/inspinia_admin-v1.8/form_advanced.html)|[Y](https://material.angularjs.org/latest/demo/slider)| | | | |
[Style guide for code](https://github.com/Swiip/generator-gulp-angular/pull/469)| |[Y](https://angular.io/docs/ts/latest/guide/style-guide.html)| | | |
[Tabs](http://208.68.38.122/themes/emerald/dev/htmls/elements/nav.html)|[Y](https://material.angularjs.org/latest/demo/switch)| | | | |
[There is a book about it](http://www.amazon.com/MEAN-Web-Development-Amos-Haviv-ebook/dp/B00NXWI1BM/ref=dp_kinw_strp_1)| | | |[Y](http://angular-2-training-book.rangle.io/)| |
[Timepicker](http://valor-software.com/ng2-bootstrap/#/timepicker)|[Y](http://valor-software.com/ng2-bootstrap/#/timepicker)| | | | |
[Tooltips](https://material.angularjs.org/latest/demo/tooltip)|[Y](https://material.angularjs.org/latest/demo/tooltip)| | | | |
[Typeahead (autocomplete) fields](http://www.quora.com/What-is-the-best-open-source-solution-for-implementing-fast-auto-complete)|[Y](https://material.angularjs.org/latest/demo/autocomplete)| | | | |
[Update generated code in an existing app](https://github.com/angular/angular-cli#updating-angular-cli)|[Y](https://github.com/angular/angular-cli#updating-angular-cli)|[Y](https://github.com/angular/angular-cli#updating-angular-cli)| | | |

**Comment by born2net** [comment]
totally agree and appreciate the effort... 
regards
