### ISSUE TITLE
Fix 'No provider for ToastsManager!' error

### ISSUE THREAD

**Issue by cde-v** [born2net/Angular-kitchen-sink#35]
in app.module.ts line 359 needs to be changed to ToastModule.forRoot(),

**Comment by martingula** [comment]
Correct solution is something like this
in app.module.ts line 359 

ToastModule.forRoot(new ToastOptions({
                            animate: 'flyRight',
                            positionClass: 'toast-bottom-right',
                            }))

**Comment by born2net** [comment]
tx fixed!
