### ISSUE TITLE
How to use credit service with an input?

### ISSUE THREAD

**Issue by alexc101** [born2net/Angular-kitchen-sink#39]
Is there an example on how to attach the service to an input? Been trying to call the service through (input) / (keydown) etc inside a custom directive but not having much luck and can't find anything in the repo which shows how it works.

(https://github.com/born2net/Angular-kitchen-sink/blob/master/src/services/CreditService.ts)

Sorry if this is inappropriate - thanks!

**Comment by born2net** [comment]
simply import in the constructor: ```constructor(private cc:CreditService)```
and call appropriate methods
```cc.validateCardNumber('4111111111111111')```
